(ns klondike.protocol)

(defprotocol IPile
  (acquire-card [this card])
  (remove-all-cards [this]))

(defprotocol ICanMoveCard
  (can-move-card [this card]))

(defprotocol ICanAcceptCard
  (can-accept-card [this card]))

(defprotocol IRemoveCard
  (remove-card [this card]))

(defprotocol IReturnCard
  (return-card [this card]))

(defprotocol ITablePile
  (flip-top-card [this])
  (lay-out-cards [this])
  (cards-on-top [this card]))